name: Build and publish Docker image

on:
  workflow_dispatch:
  push:
    paths:
      - "versions.json"
    branches:
      - master

jobs:
  push_to_registry:
    name: Push Docker image to docker hub
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.message, ' bump versions ') || github.event_name == 'workflow_dispatch' }}

    permissions:
      packages: write
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}

      - name: Build Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: |
            ${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:latest

      - name: Push Docker images
        if: success()
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:latest
